name: Update README with Latest WordPress Posts

on:
  schedule:
    - cron: "* * * * *" # Runs every minute, adjust as needed
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest posts from WordPress API
        run: |
          curl -s https://techfacts007.in/wp-json/wp/v2/posts?per_page=5 > posts.json
          jq -r '[.[] | {title: .title.rendered, link: .link}]' posts.json > latest_posts.json

      - name: Create new content file
        run: |
          cat latest_posts.json | jq -r '.[] | "- [\(.title)](\(.link))"' > new_content.md

      - name: Update README.md with latest posts
        run: |
          awk '/### Latest Posts/ {in_section=1; print; next} /###/ {in_section=0} in_section {next} {print}' README.md > temp.md
          echo -e "\n### Latest Posts\n" >> temp.md
          cat new_content.md >> temp.md
          mv temp.md README.md
          git config --global user.email "shanuraj715@gmail.com"
          git config --global user.name "shanuraj715"
          git add README.md
          git commit -m "Update README with latest posts"
          git push
